title: D&D 5th — Ruleset
email: senorigl@gmail.com
description: >-
  A compilation of all rules for Dungeons & Dragons 5th edition
baseurl: "/dnd-5e-ruleset"
url: ""
twitter_username: senorihl
github_username: senorihl

theme: "just-the-docs"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  docs:
    permalink: "/:collection/:slug/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation

exclude:
  - "generator/"
  - "node_modules/"

footer_content: 'Proposed by <a href="https://github.com/senorihl" target=_blank>Senorihl</a>. Distributed <a href="https://github.com/senorihl/dnd-5e-ruleset/tree/main/LICENSE.txt">Unlicensed.</a>'
